import 'package:finalproject/components/custom_widgets.dart';
import 'package:finalproject/screens/fade_animation.dart';
import 'package:flutter/material.dart';
import 'package:lottie/lottie.dart';

class PasswordChange extends StatefulWidget {
  const PasswordChange({super.key});

  @override
  State<PasswordChange> createState() => _PasswordChangeState();
}

class _PasswordChangeState extends State<PasswordChange> {
  @override
  Widget build(BuildContext context) {
    return  Scaffold(
      body: SafeArea(child: Column(
        children: [
          //This is a widget that displays an animation in the JSON format generated by the Lottie library
          LottieBuilder.asset("assets/images/ticker.json"),
          const FadeAnimation(
             delay: 1,
            child: Text(            
            'password has been changed !!',
            style: TextStyle(
               fontSize: 25,
                fontFamily: "Urbanist",
                fontWeight: FontWeight.bold,
            )
            ),
          ),
            const SizedBox(
              height: 20,),
            const FadeAnimation(
               delay:0,
               child: Text('Password has been changed successfully',
                    style: TextStyle(
                      fontSize: 20,
                        fontFamily: 'Urbanist-Bold',
                          fontWeight: FontWeight.w500,
                          color: Colors.black 
            ),),),
    const SizedBox(
      height: 20,
    ),
    FadeAnimation(
      delay: 1,
      child: CustomElevatedButton(
        message: "Back to Login Page", 
      function:(){},
       color: Colors.black,
       ),
        ),



        ],
      )),
    );
  }
}
